name: Créer des versions de production

jobs:
  build_android:
    type: build
    settings:
      platform: android
      profile: production
  build_ios:
    type: build
    settings:
      platform: ios
      profile: production
